// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: lobby_api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LobbyState int32

const (
	LobbyState_IN_LOBBY LobbyState = 0
	LobbyState_IN_GAME  LobbyState = 1
)

// Enum value maps for LobbyState.
var (
	LobbyState_name = map[int32]string{
		0: "IN_LOBBY",
		1: "IN_GAME",
	}
	LobbyState_value = map[string]int32{
		"IN_LOBBY": 0,
		"IN_GAME":  1,
	}
)

func (x LobbyState) Enum() *LobbyState {
	p := new(LobbyState)
	*p = x
	return p
}

func (x LobbyState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LobbyState) Descriptor() protoreflect.EnumDescriptor {
	return file_lobby_api_proto_enumTypes[0].Descriptor()
}

func (LobbyState) Type() protoreflect.EnumType {
	return &file_lobby_api_proto_enumTypes[0]
}

func (x LobbyState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LobbyState.Descriptor instead.
func (LobbyState) EnumDescriptor() ([]byte, []int) {
	return file_lobby_api_proto_rawDescGZIP(), []int{0}
}

type BellType int32

const (
	BellType_BING BellType = 0
	BellType_BONG BellType = 1
)

// Enum value maps for BellType.
var (
	BellType_name = map[int32]string{
		0: "BING",
		1: "BONG",
	}
	BellType_value = map[string]int32{
		"BING": 0,
		"BONG": 1,
	}
)

func (x BellType) Enum() *BellType {
	p := new(BellType)
	*p = x
	return p
}

func (x BellType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BellType) Descriptor() protoreflect.EnumDescriptor {
	return file_lobby_api_proto_enumTypes[1].Descriptor()
}

func (BellType) Type() protoreflect.EnumType {
	return &file_lobby_api_proto_enumTypes[1]
}

func (x BellType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BellType.Descriptor instead.
func (BellType) EnumDescriptor() ([]byte, []int) {
	return file_lobby_api_proto_rawDescGZIP(), []int{1}
}

type RegisterPlayerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *RegisterPlayerRequest) Reset() {
	*x = RegisterPlayerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPlayerRequest) ProtoMessage() {}

func (x *RegisterPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPlayerRequest.ProtoReflect.Descriptor instead.
func (*RegisterPlayerRequest) Descriptor() ([]byte, []int) {
	return file_lobby_api_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterPlayerRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type RegisterPlayerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *RegisterPlayerResponse) Reset() {
	*x = RegisterPlayerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterPlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPlayerResponse) ProtoMessage() {}

func (x *RegisterPlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPlayerResponse.ProtoReflect.Descriptor instead.
func (*RegisterPlayerResponse) Descriptor() ([]byte, []int) {
	return file_lobby_api_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterPlayerResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type LoginPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *LoginPlayer) Reset() {
	*x = LoginPlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginPlayer) ProtoMessage() {}

func (x *LoginPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginPlayer.ProtoReflect.Descriptor instead.
func (*LoginPlayer) Descriptor() ([]byte, []int) {
	return file_lobby_api_proto_rawDescGZIP(), []int{2}
}

func (x *LoginPlayer) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type CreateLobby struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateLobby) Reset() {
	*x = CreateLobby{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLobby) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLobby) ProtoMessage() {}

func (x *CreateLobby) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLobby.ProtoReflect.Descriptor instead.
func (*CreateLobby) Descriptor() ([]byte, []int) {
	return file_lobby_api_proto_rawDescGZIP(), []int{3}
}

func (x *CreateLobby) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type JoinLobby struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *JoinLobby) Reset() {
	*x = JoinLobby{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinLobby) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinLobby) ProtoMessage() {}

func (x *JoinLobby) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinLobby.ProtoReflect.Descriptor instead.
func (*JoinLobby) Descriptor() ([]byte, []int) {
	return file_lobby_api_proto_rawDescGZIP(), []int{4}
}

func (x *JoinLobby) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LeaveLobby struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LeaveLobby) Reset() {
	*x = LeaveLobby{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveLobby) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveLobby) ProtoMessage() {}

func (x *LeaveLobby) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveLobby.ProtoReflect.Descriptor instead.
func (*LeaveLobby) Descriptor() ([]byte, []int) {
	return file_lobby_api_proto_rawDescGZIP(), []int{5}
}

type RequestRingBell struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BellType BellType `protobuf:"varint,1,opt,name=bell_type,json=bellType,proto3,enum=api.BellType" json:"bell_type,omitempty"`
}

func (x *RequestRingBell) Reset() {
	*x = RequestRingBell{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestRingBell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRingBell) ProtoMessage() {}

func (x *RequestRingBell) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRingBell.ProtoReflect.Descriptor instead.
func (*RequestRingBell) Descriptor() ([]byte, []int) {
	return file_lobby_api_proto_rawDescGZIP(), []int{6}
}

func (x *RequestRingBell) GetBellType() BellType {
	if x != nil {
		return x.BellType
	}
	return BellType_BING
}

type LobbyList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LobbyList []string `protobuf:"bytes,1,rep,name=lobby_list,json=lobbyList,proto3" json:"lobby_list,omitempty"`
}

func (x *LobbyList) Reset() {
	*x = LobbyList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LobbyList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyList) ProtoMessage() {}

func (x *LobbyList) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyList.ProtoReflect.Descriptor instead.
func (*LobbyList) Descriptor() ([]byte, []int) {
	return file_lobby_api_proto_rawDescGZIP(), []int{7}
}

func (x *LobbyList) GetLobbyList() []string {
	if x != nil {
		return x.LobbyList
	}
	return nil
}

type LobbyDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	State      LobbyState `protobuf:"varint,2,opt,name=state,proto3,enum=api.LobbyState" json:"state,omitempty"`
	PlayerList []string   `protobuf:"bytes,3,rep,name=player_list,json=playerList,proto3" json:"player_list,omitempty"`
}

func (x *LobbyDetails) Reset() {
	*x = LobbyDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LobbyDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyDetails) ProtoMessage() {}

func (x *LobbyDetails) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyDetails.ProtoReflect.Descriptor instead.
func (*LobbyDetails) Descriptor() ([]byte, []int) {
	return file_lobby_api_proto_rawDescGZIP(), []int{8}
}

func (x *LobbyDetails) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LobbyDetails) GetState() LobbyState {
	if x != nil {
		return x.State
	}
	return LobbyState_IN_LOBBY
}

func (x *LobbyDetails) GetPlayerList() []string {
	if x != nil {
		return x.PlayerList
	}
	return nil
}

type RingBellEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BellType BellType `protobuf:"varint,1,opt,name=bell_type,json=bellType,proto3,enum=api.BellType" json:"bell_type,omitempty"`
}

func (x *RingBellEvent) Reset() {
	*x = RingBellEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RingBellEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RingBellEvent) ProtoMessage() {}

func (x *RingBellEvent) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RingBellEvent.ProtoReflect.Descriptor instead.
func (*RingBellEvent) Descriptor() ([]byte, []int) {
	return file_lobby_api_proto_rawDescGZIP(), []int{9}
}

func (x *RingBellEvent) GetBellType() BellType {
	if x != nil {
		return x.BellType
	}
	return BellType_BING
}

type FailEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info string `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *FailEvent) Reset() {
	*x = FailEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FailEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailEvent) ProtoMessage() {}

func (x *FailEvent) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailEvent.ProtoReflect.Descriptor instead.
func (*FailEvent) Descriptor() ([]byte, []int) {
	return file_lobby_api_proto_rawDescGZIP(), []int{10}
}

func (x *FailEvent) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

type PlayerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Action:
	//	*PlayerRequest_Login
	//	*PlayerRequest_CreateLobby
	//	*PlayerRequest_JoinLobby
	//	*PlayerRequest_LeaveLobby
	//	*PlayerRequest_RingBell
	Action isPlayerRequest_Action `protobuf_oneof:"action"`
}

func (x *PlayerRequest) Reset() {
	*x = PlayerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerRequest) ProtoMessage() {}

func (x *PlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerRequest.ProtoReflect.Descriptor instead.
func (*PlayerRequest) Descriptor() ([]byte, []int) {
	return file_lobby_api_proto_rawDescGZIP(), []int{11}
}

func (m *PlayerRequest) GetAction() isPlayerRequest_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (x *PlayerRequest) GetLogin() *LoginPlayer {
	if x, ok := x.GetAction().(*PlayerRequest_Login); ok {
		return x.Login
	}
	return nil
}

func (x *PlayerRequest) GetCreateLobby() *CreateLobby {
	if x, ok := x.GetAction().(*PlayerRequest_CreateLobby); ok {
		return x.CreateLobby
	}
	return nil
}

func (x *PlayerRequest) GetJoinLobby() *JoinLobby {
	if x, ok := x.GetAction().(*PlayerRequest_JoinLobby); ok {
		return x.JoinLobby
	}
	return nil
}

func (x *PlayerRequest) GetLeaveLobby() *LeaveLobby {
	if x, ok := x.GetAction().(*PlayerRequest_LeaveLobby); ok {
		return x.LeaveLobby
	}
	return nil
}

func (x *PlayerRequest) GetRingBell() *RequestRingBell {
	if x, ok := x.GetAction().(*PlayerRequest_RingBell); ok {
		return x.RingBell
	}
	return nil
}

type isPlayerRequest_Action interface {
	isPlayerRequest_Action()
}

type PlayerRequest_Login struct {
	Login *LoginPlayer `protobuf:"bytes,1,opt,name=login,proto3,oneof"`
}

type PlayerRequest_CreateLobby struct {
	CreateLobby *CreateLobby `protobuf:"bytes,2,opt,name=create_lobby,json=createLobby,proto3,oneof"`
}

type PlayerRequest_JoinLobby struct {
	JoinLobby *JoinLobby `protobuf:"bytes,3,opt,name=join_lobby,json=joinLobby,proto3,oneof"`
}

type PlayerRequest_LeaveLobby struct {
	LeaveLobby *LeaveLobby `protobuf:"bytes,4,opt,name=leave_lobby,json=leaveLobby,proto3,oneof"`
}

type PlayerRequest_RingBell struct {
	RingBell *RequestRingBell `protobuf:"bytes,5,opt,name=ring_bell,json=ringBell,proto3,oneof"`
}

func (*PlayerRequest_Login) isPlayerRequest_Action() {}

func (*PlayerRequest_CreateLobby) isPlayerRequest_Action() {}

func (*PlayerRequest_JoinLobby) isPlayerRequest_Action() {}

func (*PlayerRequest_LeaveLobby) isPlayerRequest_Action() {}

func (*PlayerRequest_RingBell) isPlayerRequest_Action() {}

type LobbyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Action:
	//	*LobbyResponse_LobbyDetails
	//	*LobbyResponse_RingBellEvent
	//	*LobbyResponse_FailEvent
	//	*LobbyResponse_LobbyList
	Action isLobbyResponse_Action `protobuf_oneof:"action"`
}

func (x *LobbyResponse) Reset() {
	*x = LobbyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LobbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyResponse) ProtoMessage() {}

func (x *LobbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyResponse.ProtoReflect.Descriptor instead.
func (*LobbyResponse) Descriptor() ([]byte, []int) {
	return file_lobby_api_proto_rawDescGZIP(), []int{12}
}

func (m *LobbyResponse) GetAction() isLobbyResponse_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (x *LobbyResponse) GetLobbyDetails() *LobbyDetails {
	if x, ok := x.GetAction().(*LobbyResponse_LobbyDetails); ok {
		return x.LobbyDetails
	}
	return nil
}

func (x *LobbyResponse) GetRingBellEvent() *RingBellEvent {
	if x, ok := x.GetAction().(*LobbyResponse_RingBellEvent); ok {
		return x.RingBellEvent
	}
	return nil
}

func (x *LobbyResponse) GetFailEvent() *FailEvent {
	if x, ok := x.GetAction().(*LobbyResponse_FailEvent); ok {
		return x.FailEvent
	}
	return nil
}

func (x *LobbyResponse) GetLobbyList() *LobbyList {
	if x, ok := x.GetAction().(*LobbyResponse_LobbyList); ok {
		return x.LobbyList
	}
	return nil
}

type isLobbyResponse_Action interface {
	isLobbyResponse_Action()
}

type LobbyResponse_LobbyDetails struct {
	LobbyDetails *LobbyDetails `protobuf:"bytes,1,opt,name=lobby_details,json=lobbyDetails,proto3,oneof"`
}

type LobbyResponse_RingBellEvent struct {
	RingBellEvent *RingBellEvent `protobuf:"bytes,2,opt,name=ring_bell_event,json=ringBellEvent,proto3,oneof"`
}

type LobbyResponse_FailEvent struct {
	FailEvent *FailEvent `protobuf:"bytes,3,opt,name=fail_event,json=failEvent,proto3,oneof"`
}

type LobbyResponse_LobbyList struct {
	LobbyList *LobbyList `protobuf:"bytes,4,opt,name=lobby_list,json=lobbyList,proto3,oneof"`
}

func (*LobbyResponse_LobbyDetails) isLobbyResponse_Action() {}

func (*LobbyResponse_RingBellEvent) isLobbyResponse_Action() {}

func (*LobbyResponse_FailEvent) isLobbyResponse_Action() {}

func (*LobbyResponse_LobbyList) isLobbyResponse_Action() {}

var File_lobby_api_proto protoreflect.FileDescriptor

var file_lobby_api_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x33, 0x0a, 0x15, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x34, 0x0a, 0x16, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x29, 0x0a, 0x0b, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x21, 0x0a, 0x0b,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x1f, 0x0a, 0x09, 0x4a, 0x6f, 0x69, 0x6e, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x0c, 0x0a, 0x0a, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x22, 0x3d,
	0x0a, 0x0f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x69, 0x6e, 0x67, 0x42, 0x65, 0x6c,
	0x6c, 0x12, 0x2a, 0x0a, 0x09, 0x62, 0x65, 0x6c, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x65, 0x6c, 0x6c, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x08, 0x62, 0x65, 0x6c, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x22, 0x2a, 0x0a,
	0x09, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x6f,
	0x62, 0x62, 0x79, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09,
	0x6c, 0x6f, 0x62, 0x62, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x6a, 0x0a, 0x0c, 0x4c, 0x6f, 0x62,
	0x62, 0x79, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x3b, 0x0a, 0x0d, 0x52, 0x69, 0x6e, 0x67, 0x42, 0x65, 0x6c,
	0x6c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x2a, 0x0a, 0x09, 0x62, 0x65, 0x6c, 0x6c, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x42, 0x65, 0x6c, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x62, 0x65, 0x6c, 0x6c, 0x54, 0x79,
	0x70, 0x65, 0x22, 0x1f, 0x0a, 0x09, 0x46, 0x61, 0x69, 0x6c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69,
	0x6e, 0x66, 0x6f, 0x22, 0x94, 0x02, 0x0a, 0x0d, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x48, 0x00, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12,
	0x35, 0x0a, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x48, 0x00, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x12, 0x2f, 0x0a, 0x0a, 0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x6c,
	0x6f, 0x62, 0x62, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x48, 0x00, 0x52, 0x09, 0x6a, 0x6f,
	0x69, 0x6e, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x12, 0x32, 0x0a, 0x0b, 0x6c, 0x65, 0x61, 0x76, 0x65,
	0x5f, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x48, 0x00, 0x52,
	0x0a, 0x6c, 0x65, 0x61, 0x76, 0x65, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x12, 0x33, 0x0a, 0x09, 0x72,
	0x69, 0x6e, 0x67, 0x5f, 0x62, 0x65, 0x6c, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x69, 0x6e, 0x67,
	0x42, 0x65, 0x6c, 0x6c, 0x48, 0x00, 0x52, 0x08, 0x72, 0x69, 0x6e, 0x67, 0x42, 0x65, 0x6c, 0x6c,
	0x42, 0x08, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xf3, 0x01, 0x0a, 0x0d, 0x4c,
	0x6f, 0x62, 0x62, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x0d,
	0x6c, 0x6f, 0x62, 0x62, 0x79, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x48, 0x00, 0x52, 0x0c, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x3c, 0x0a, 0x0f, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x62,
	0x65, 0x6c, 0x6c, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x69, 0x6e, 0x67, 0x42, 0x65, 0x6c, 0x6c, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0d, 0x72, 0x69, 0x6e, 0x67, 0x42, 0x65, 0x6c, 0x6c, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x2f, 0x0a, 0x0a, 0x66, 0x61, 0x69, 0x6c, 0x5f, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x46,
	0x61, 0x69, 0x6c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x09, 0x66, 0x61, 0x69, 0x6c,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x2f, 0x0a, 0x0a, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x5f, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x4c, 0x6f, 0x62, 0x62, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x09, 0x6c, 0x6f, 0x62,
	0x62, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x08, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2a, 0x27, 0x0a, 0x0a, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0c,
	0x0a, 0x08, 0x49, 0x4e, 0x5f, 0x4c, 0x4f, 0x42, 0x42, 0x59, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07,
	0x49, 0x4e, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x10, 0x01, 0x2a, 0x1e, 0x0a, 0x08, 0x42, 0x65, 0x6c,
	0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12,
	0x08, 0x0a, 0x04, 0x42, 0x4f, 0x4e, 0x47, 0x10, 0x01, 0x32, 0x98, 0x01, 0x0a, 0x0c, 0x4c, 0x6f,
	0x62, 0x62, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4b, 0x0a, 0x0e, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x1a, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x0b, 0x4c, 0x6f, 0x62, 0x62, 0x79,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x12, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x28, 0x01, 0x30, 0x01, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x67, 0x61, 0x6d,
	0x65, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2d, 0x62, 0x6f, 0x69, 0x6c, 0x65, 0x72, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lobby_api_proto_rawDescOnce sync.Once
	file_lobby_api_proto_rawDescData = file_lobby_api_proto_rawDesc
)

func file_lobby_api_proto_rawDescGZIP() []byte {
	file_lobby_api_proto_rawDescOnce.Do(func() {
		file_lobby_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_lobby_api_proto_rawDescData)
	})
	return file_lobby_api_proto_rawDescData
}

var file_lobby_api_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_lobby_api_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_lobby_api_proto_goTypes = []interface{}{
	(LobbyState)(0),                // 0: api.LobbyState
	(BellType)(0),                  // 1: api.BellType
	(*RegisterPlayerRequest)(nil),  // 2: api.RegisterPlayerRequest
	(*RegisterPlayerResponse)(nil), // 3: api.RegisterPlayerResponse
	(*LoginPlayer)(nil),            // 4: api.LoginPlayer
	(*CreateLobby)(nil),            // 5: api.CreateLobby
	(*JoinLobby)(nil),              // 6: api.JoinLobby
	(*LeaveLobby)(nil),             // 7: api.LeaveLobby
	(*RequestRingBell)(nil),        // 8: api.RequestRingBell
	(*LobbyList)(nil),              // 9: api.LobbyList
	(*LobbyDetails)(nil),           // 10: api.LobbyDetails
	(*RingBellEvent)(nil),          // 11: api.RingBellEvent
	(*FailEvent)(nil),              // 12: api.FailEvent
	(*PlayerRequest)(nil),          // 13: api.PlayerRequest
	(*LobbyResponse)(nil),          // 14: api.LobbyResponse
}
var file_lobby_api_proto_depIdxs = []int32{
	1,  // 0: api.RequestRingBell.bell_type:type_name -> api.BellType
	0,  // 1: api.LobbyDetails.state:type_name -> api.LobbyState
	1,  // 2: api.RingBellEvent.bell_type:type_name -> api.BellType
	4,  // 3: api.PlayerRequest.login:type_name -> api.LoginPlayer
	5,  // 4: api.PlayerRequest.create_lobby:type_name -> api.CreateLobby
	6,  // 5: api.PlayerRequest.join_lobby:type_name -> api.JoinLobby
	7,  // 6: api.PlayerRequest.leave_lobby:type_name -> api.LeaveLobby
	8,  // 7: api.PlayerRequest.ring_bell:type_name -> api.RequestRingBell
	10, // 8: api.LobbyResponse.lobby_details:type_name -> api.LobbyDetails
	11, // 9: api.LobbyResponse.ring_bell_event:type_name -> api.RingBellEvent
	12, // 10: api.LobbyResponse.fail_event:type_name -> api.FailEvent
	9,  // 11: api.LobbyResponse.lobby_list:type_name -> api.LobbyList
	2,  // 12: api.LobbyService.RegisterPlayer:input_type -> api.RegisterPlayerRequest
	13, // 13: api.LobbyService.LobbyStream:input_type -> api.PlayerRequest
	3,  // 14: api.LobbyService.RegisterPlayer:output_type -> api.RegisterPlayerResponse
	14, // 15: api.LobbyService.LobbyStream:output_type -> api.LobbyResponse
	14, // [14:16] is the sub-list for method output_type
	12, // [12:14] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_lobby_api_proto_init() }
func file_lobby_api_proto_init() {
	if File_lobby_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lobby_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterPlayerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterPlayerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginPlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLobby); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinLobby); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveLobby); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestRingBell); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LobbyList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LobbyDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RingBellEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FailEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_api_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_api_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LobbyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_lobby_api_proto_msgTypes[11].OneofWrappers = []interface{}{
		(*PlayerRequest_Login)(nil),
		(*PlayerRequest_CreateLobby)(nil),
		(*PlayerRequest_JoinLobby)(nil),
		(*PlayerRequest_LeaveLobby)(nil),
		(*PlayerRequest_RingBell)(nil),
	}
	file_lobby_api_proto_msgTypes[12].OneofWrappers = []interface{}{
		(*LobbyResponse_LobbyDetails)(nil),
		(*LobbyResponse_RingBellEvent)(nil),
		(*LobbyResponse_FailEvent)(nil),
		(*LobbyResponse_LobbyList)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lobby_api_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lobby_api_proto_goTypes,
		DependencyIndexes: file_lobby_api_proto_depIdxs,
		EnumInfos:         file_lobby_api_proto_enumTypes,
		MessageInfos:      file_lobby_api_proto_msgTypes,
	}.Build()
	File_lobby_api_proto = out.File
	file_lobby_api_proto_rawDesc = nil
	file_lobby_api_proto_goTypes = nil
	file_lobby_api_proto_depIdxs = nil
}
